### ISSUE TITLE
Unzip CODE-VINE

### ISSUE THREAD

**Issue by gohna** [NagabhushanSN95/nagabhushansn95.github.io#1]
I hope to learn the CODE-VINE, but here it needs a password to unzip files. The tips show that the password can be found in some readme files, however i can's find this file. Thank you!

**Comment by NagabhushanSN95** [comment]
Hi, thanks for your interest in our work. Kindly send a mail to my email address "nagabhushans@iisc.ac.in". I'll share the password.
